// Generates src/components/icons.tsx from inline SVGs in docs/research/pay-home.html
import fs from "node:fs";

const html = fs.readFileSync("docs/research/pay-home.html", "utf8");
const matches = [...html.matchAll(/<svg[\s\S]*?<\/svg>/g)].map((m) => m[0]);

// unique svgs by content, named by position/context
const picks = [
  { idx: 0, name: "ChevronDownIcon" },        // nav dropdown chevron
  { idx: 8, name: "EmbeddedCheckoutIcon" },   // hero tab 1
  { idx: 9, name: "RoutingIcon" },            // hero tab 2
  { idx: 10, name: "AutomationIcon" },        // hero tab 3
  { idx: 11, name: "ReconciliationIcon" },    // hero tab 4
  { idx: 12, name: "OperationalVisibilityIcon" }, // hero tab 5
  { idx: 13, name: "RoiChevronIcon" },
  { idx: 14, name: "InputErrorIcon" },
  { idx: 16, name: "FlagUsdIcon" },
  { idx: 17, name: "FlagGbpIcon" },
  { idx: 18, name: "FlagEurIcon" },
  { idx: 19, name: "TrendUpIcon" },
  { idx: 20, name: "RoiCheckIcon" },
  { idx: 21, name: "CloseIcon" },
];

function toJsx(svg, name) {
  let s = svg;
  // unescape any html entities in attrs
  s = s.replace(/&quot;/g, '"').replace(/&amp;/g, "&");
  // kebab-case attrs → camelCase
  const attrMap = {
    "clip-path": "clipPath", "clip-rule": "clipRule", "fill-rule": "fillRule",
    "stroke-width": "strokeWidth", "stroke-linecap": "strokeLinecap",
    "stroke-linejoin": "strokeLinejoin", "stroke-dasharray": "strokeDasharray",
    "stroke-miterlimit": "strokeMiterlimit", "fill-opacity": "fillOpacity",
    "stop-color": "stopColor", "stop-opacity": "stopOpacity",
    "xmlns:xlink": "xmlnsXlink", "xlink:href": "xlinkHref",
    "maskUnits": "maskUnits", "mask-type": "maskType",
  };
  for (const [k, v] of Object.entries(attrMap)) {
    s = s.replaceAll(`${k}=`, `${v}=`);
  }
  // style="a:b;c:d" → style={{a:'b',c:'d'}}
  s = s.replace(/style="([^"]*)"/g, (_, css) => {
    const obj = css
      .split(";")
      .map((d) => d.trim())
      .filter(Boolean)
      .map((d) => {
        const ci = d.indexOf(":");
        const prop = d.slice(0, ci).trim().replace(/-([a-z])/g, (_, c) => c.toUpperCase());
        const val = d.slice(ci + 1).trim();
        return `${prop}: '${val}'`;
      })
      .join(", ");
    return `style={{ ${obj} }}`;
  });
  // class= → className=
  s = s.replaceAll("class=", "className=");
  // make ids unique per component to avoid collisions
  s = s.replace(/id="([^"]+)"/g, (_, id) => `id="${name}-${id}"`);
  s = s.replace(/url\(#([^)]+)\)/g, (_, id) => `url(#${name}-${id})`);
  s = s.replace(/href="#([^"]+)"/g, (_, id) => `href="#${name}-${id}"`);
  // spread props onto root svg
  s = s.replace(/^<svg /, "<svg {...props} ");
  return s;
}

let out = `// Extracted SVG icons from pay.com (auto-generated by scripts/gen-icons.mjs)
import type { SVGProps } from "react";

type IconProps = SVGProps<SVGSVGElement>;
`;

for (const { idx, name } of picks) {
  const svg = matches[idx];
  if (!svg) {
    console.error("missing svg at index", idx);
    continue;
  }
  out += `
export function ${name}(props: IconProps) {
  return (
    ${toJsx(svg, name)}
  );
}
`;
}

fs.writeFileSync("src/components/icons.tsx", out);
console.log("wrote src/components/icons.tsx with", picks.length, "icons");
